### ISSUE TITLE
Remove the "n" from whitelisted tokens

### ISSUE THREAD

**Issue by kcole16** [ref-finance/ref-ui#102]
### Overview

We should hide the "n" from tokens like nETH that are whitelisted, and instead just show "ETH". Several users have reported this as confusing, and it benefits Ref if users feel like they are using "real ETH".

### Acceptance
- [x] For tokens on the whitelist, the "n" is parsed and doesn't appear (nETH shows as ETH)
- [x] wNEAR is displayed as NEAR

**Comment by mohamedalichelbi** [comment]
@kcole16 I think the problem is, there is no token called ETH (/ WETH) on near. It's called nETH (/ nWETH) according to the contract's metadata. I agree with you that it's confusing, but the better solution is to discuss this with the rainbow bridge guys.
