### ISSUE TITLE
Display TVL for alt/alt pools

### ISSUE THREAD

**Issue by TiGowa** [ref-finance/ref-ui#121]
alt definition: non wNEAR, non ERC20
alt pool example: GTC/marmaj
[
![Screenshot_20210731-093055](https://user-images.githubusercontent.com/46521065/127748039-05ac817e-c76b-45cc-b40b-3411b163f939.png)
](url)

**Comment by marco-sundsk** [comment]
About this TVL thing, it is actually a global-whitelist issue. 

Let us think this way, if a TVL displays on the app, users would think the backend assets, those two tokens, are what they think they are. But in fact, cause anyone can build a swap pool in ref with any tokens, there is no guarantee that these tokens are not faked ones. 

So, we bring up a global-whitelist schema which we includes all tokens we recognized as genuine. And we only fetch price of those in that list. That in turn, cause some pool without TVL value.

As a conclusion, if someone want add TVL for a specific pool, he can check if the two tokens are in glboal-whitelist. If not, an application for adding to global-whitelist is need for further service like TVL.

**Comment by TiGowa** [comment]
That's a good point. Let me think of a questionnaire / procedure / application for anyone who wants to add a token in the whitelist. The request can come directly from a user and / or from the core team. If the decision comes from the core team, then we need to have an internal due diligence. I will make some suggestions.

**Comment by marco-sundsk** [comment]
Right, basically, a google form or a github issue with specific format would be used as application form, and open to public. Then the DAO would take over to evaluate them.
