### ISSUE TITLE
Frontend not finding REF balance

### ISSUE THREAD

**Issue by mikedotexe** [ref-finance/ref-ui#142]
As can be shown in the video from this Discord post:

https://discord.com/channels/831453845833383957/841209516451692544/886402597991383070

The REF token balance showing up in NEAR Wallet and via NEAR CLI commands does not show up in the UI.

**Comment by benjamingreenberg** [comment]
You need to deposit the REF into your ref finance account first. Click the drop-down in the deposit page, choose REF (even if it has a zero next to it). you should then be able to see your balance and deposit it.
