### ISSUE TITLE
Can submit swap form before swap rate update completes 

### ISSUE THREAD

**Issue by benjamingreenberg** [ref-finance/ref-ui#143]
This is regarding an issue a user had when swapping near for oct on 09/16/2021 at 13:12:34 UTC. The swap was done on pool 21. They deposited 220N and received 525 OCT (2.386 OCT/NEAR). Pool 47 has several orders of magnitude more liquidity than 21 and seems to have had a swap rate around 3.5-4 OCT/NEAR consistently for a couple of weeks. If it was around that rate at the time of the swap, it would have returned around 800 oct.

Here is a link to the message in the Dev on Ref-Finance support channel reporting this issue: https://t.me/dev_on_ref_finance/117

Link to the transaction in the near explorer: https://explorer.mainnet.near.org/transactions/4k6LNCtw1wAc4oA65S8wtgohpg3owdxFyvAjCGW1mSui

Another user reported a similar experience swapping from OCT to wNEAR: https://t.me/ref_finance/44158
https://explorer.near.org/transactions/9Zn4quNvJ5ZFrNtUhumPuaGcbZCN5EzHAVMxfaRR219K

If you look at the tx from the first incident in the explorer, the minimum amount out is only 0.253 OCT. This is particularly strange because 0.253 is an amount you'd expect to see if you were swapping 1 OCT for NEAR. It's like the form was originally set to swap OCT to NEAR, with the From value set to the default "1", Minimum received  set to .253, and the pool set to 21. The user then clicked the arrow to change the swap order, entered 220 for the From amount, and submitted the form with the Minimum received still at .253 and the pool still at 21. The page normally disables submitting the form when the user changes the input amount, and doesn't re-enable it until the new swap rate/pool are retrieved. However, there are moments when the form is capable of being submitted with the old minimum received and pool.  

I cloned ref-ui, and placed console.log calls immediately before the return statement of the SwapCard component (src/components/swap/SwapCard.tsx), that output the values of canSwap, tokenIn.symbol, tokenOut.symbol, tokenInAmount, minAmountOut, and pool.id. 

Testnet contains a RFT/wNEAR pool (0) with a lot of liquidity and a 0.4% fee. I created another pool (8) with less liquidity and a 0.2% fee. I set the form to swap 1 RFT to wNEAR, and the system selected pool 8 with a minimum received of 0.0256. I then clicked the arrow to switch tokens, and quickly set the From amount to 10 wNEAR. The console showed times when canSwap=true, tokenIn=wNEAR, tokenOut=RFT, tokenInAmount=10, minAmountOut=0.0256, and pool.id=8: [localhost-1632029002509.log](https://github.com/ref-finance/ref-ui/files/7191063/localhost-1632029002509.log)

I wasn't fast enough to be able to submit the form during these moments, but it may be possible if someone's system is slow or low on resources causing longer delays between the component updates.

I wonder if it makes sense to create a smart contract for the swap that isn't given the pool id. Instead it is given the ids for all pools containing the swap pair, and it finds the pool with the best swap rate at that time.

Another issue I noticed was that ref is configured to periodically update the swap rate even if the user hasn't changed any inputs. I don't think this is a good idea. It is possible for the swap rate to be updated a fraction of a second before the user submits the form, which could result in a swap for a different rate than what the user expected. The swap rate should never be updated unless the user has made a change to an input.

**Comment by aidai524** [comment]
Hey @benjamingreenberg thanks for your feedback and spending so much time debugging and locating the problem. We also found this problem, and we can effectively avoid such problems by controlling the frequency of user input. We will open to the mainnet environment for some users to testing asap.

> Another issue I noticed was that ref is configured to periodically update the swap rate even if the user hasn't changed any inputs. I don't think this is a good idea. It is possible for the swap rate to be updated a fraction of a second before the user submits the form, which could result in a swap for a different rate than what the user expected. The swap rate should never be updated unless the user has made a change to an input.

About this pb, It’s because there were users who did not operate for a long time, which caused the exchange rate to updated, and the results after their operations were inconsistent with the results they saw, which caused a lot of confusion and complaints. So we added regular refresh to ensure that the Before clicking the swap button, try to keep the latest exchange rate for transactions.

**Comment by benjamingreenberg** [comment]
> we can effectively avoid such problems by controlling the frequency of user input.

How about setting pool to null before/during any call to estimateSwap? This should ensure that the form can never be submitted until it has been updated with the new rate, and even if it is the tx will fail. Maybe also blank out the values of tokenOutAmount, minAmountOut, and  the swap rate on the form so there is zero ambiguity about what is happening.

**Comment by marco-sundsk** [comment]
Although Benjaming's suggestion may be a good way to handle the issue, I am thinking of a different way.   

The key problem here is the mismatch between `amount_in` that user entered and `swap_rate` which ref contract responded asynchronously.  Direct solutions may focus on how to make them match by setting serious flags. But, why not we remove that asynchronous step of query `swap_rate` on chain? FE has enough info (`tokenA supply`, `tokenB supply`, `swap fee`) to caculate it by itsown.  

In this way, FE can get `swap rate` immediately (makes a very smooth responding when enter digit) and perfect match the `amount_in`. The only thing need to do is to periodically or find a good timing to update pool info to refresh tokens supply of related pools.
