### ISSUE TITLE
Remove token balances in deposit dropdown list

### ISSUE THREAD

**Issue by benjamingreenberg** [ref-finance/ref-ui#144]
The list of tokens in the select box for depositing tokens shows each token's balance in the user's Ref Finance account. There have been many posts in the support channels from users who think this number is the balance in their wallet, and believe that there is a problem with ref not being able to see their tokens in their wallet. Messages related to this increased substantially when the 4x farming incentive started. Users would go to deposit ref they withdrew from farming rewards, see that there was a "0" next to the REF token, and close the select box without clicking on the token.

I think the ideal solution would be to show the user's wallet balance for each token. However, a quick fix that can be implemented now is to not show any balances at all.  The only change necessary is in `DepositPage`, where the `TokenAmount` `balances` property should be changed to `null`. 

```
<TokenAmount
  amount={amount}
  max={max}
  total={max}
  tokens={[nearMetadata, ...tokens]}
  balances={null}
  selectedToken={selectedToken}
  onSelectToken={setSelectedToken}
  onChangeAmount={setAmount}
  calledBy="deposit"
/>
```

If this is an acceptable solution, then it would be great if it could be implemented before the next incentive promotion begins.

**Comment by aidai524** [comment]
I think we still have to solve this problem by improving the user experience instead of removing it. I will talk to our UI deisgner to improve this UI/UX.

**Comment by benjamingreenberg** [comment]
> I think we still have to solve this problem by improving the user experience instead of removing it. I will talk to our UI deisgner to improve this UI/UX.

Agreed. However if there are other priorities that would prevent the better solution from being implemented before the next incentive is announced, then I, and other mods in the rf telegram/discord groups would appreciate it if this fix could be applied.
