### ISSUE TITLE
MAX button should account for % needed for transaction

### ISSUE THREAD

**Issue by mikeymasonic** [ref-finance/ref-ui#30]
If I hit the MAX button in swap, the numbers are off and I get an error when trying to initalize the transaction.

```
requesting the transfer of
Ⓝ
9.99801
Available Balance: Ⓝ
9.99508
```

```
Sorry an error has occurred. You may want to try again.
Error: Sender mikey.near does not have enough balance 9995384510879566600000000 for operation costing 10038268808077530345929833
```

**Comment by mehtaphysical** [comment]
oh hi @mikeymasonic!

Yes agree. We'll need to recreate some of the logic from the smart contract on the front-end: https://github.com/ref-finance/ref-contracts/blob/main/ref-exchange/src/simple_pool.rs#L90.
