### ISSUE TITLE
Clicking on withdraw leads to an error on TestNet

### ISSUE THREAD

**Issue by referencedev** [ref-finance/ref-ui#32]
Steps:
1. go to https://testnet.ref.finance/
2. login
3. go to https://testnet.ref.finance/portfolio
4. Click "Withdrawal"
5. Observe error:
```
errors.js:18 Uncaught (in promise) Error: Querying call/NEAR/ft_balance_of,DHcDMR9nKJkkBNH6cvhy24vc6cHXs8TGTnHb5uceES69DSHS failed: Contract ID "NEAR" is not valid.
{
  "error": "Contract ID \"NEAR\" is not valid",
  "logs": [],
  "block_height": 43224406,
  "block_hash": "ERk7whDDfKk4TRR9T5BTYTpHFXE79QiqVRmyd9F7D4QZ"
}
    at f.query (json-rpc-provider.js:80)
    at async r.viewFunction (account.js:271)
```

**Comment by mohamedalichelbi** [comment]
@referencedev  have you tried locally changing the ID to "testnet"? had a similar problem depositing near because the frontend kept querying wrap.near which doesn't exist on testnet.
