### ISSUE TITLE
UI deposits tokens where exchange is not registered

### ISSUE THREAD

**Issue by ilblackdragon** [ref-finance/ref-ui#46]
For example: https://explorer.near.org/transactions/CCQbe9fpTFrqW1YnCbi725oA3ZDZtKHGjwaTeRWHUvfQ

If exchange is not registered in the token, the error is very unclear. Potentially UI should suggest user to register the exchange in the token when user registering this token in the exchange.

Context: for exchange to receive new token, the exchange must be registered on the token contract (deposit 0.0125N) to prevent storage blowup

**Comment by mehtaphysical** [comment]
Right now there is a check for this when a user tries to register a token not on the global whitelist.

The check is skipped for globally whitelisted tokens though, the assumption being that all globally whitelisted tokens already have storage paid for.
