### ISSUE TITLE
Adboard: Limit the price range to within x% of previous purchase, to prevent users from squatting squares

### ISSUE THREAD

**Issue by kcole16** [ref-finance/ref-ui#70]

**Comment by kcole16** [comment]
@mehtaphysical Can you add more detail to this issue? cc @aidai524 @aardvarktechnology

**Comment by mehtaphysical** [comment]
Right, when a frame is purchased the buyer can set an amount to sell the frame for. We want to make it so that the frame is resold within an acceptable range (based on a price factor).

The idea is to add this logic to the smart contract. I think @Danzondo is working on this logic.
