### ISSUE TITLE
Implement instant swap (no deposit)

### ISSUE THREAD

**Issue by kcole16** [ref-finance/ref-ui#97]
### Overview

We should implement https://github.com/ref-finance/ref-contracts/pull/30. This way, users will not need to deposit before swapping. Additionally, we will need to refactor the "Deposit" page, as it is no longer relevant.

### Acceptance Criteria
- [x] Users can swap tokens without depositing
- [x] If the user is swapping for an unregistered token, the token is first registered
- [ ] Users can add liquidity without depositing

**Comment by marco-sundsk** [comment]
> ### Overview
> We should implement [ref-finance/ref-contracts#30](https://github.com/ref-finance/ref-contracts/pull/30). This way, users will not need to deposit before swapping. Additionally, we will need to refactor the "Deposit" page, as it is no longer relevant.
> 
> ### Acceptance Criteria
> * [x]  Users can swap tokens without depositing
> * [x]  If the user is swapping for an unregistered token, the token is first registered
> * [ ]  Users can add liquidity without depositing

* Criteria 1 has been supported by contract itself, we only need to refactor the frontend;
* Criteria 2 should be implemented at frontend, if a unregistered token is swapped out, the instant swap flow would stop and the token would be in the users inner account in ref-finance contract. So, frontend should be responsible for register all possible involved token during the instant swap. 
* Criteria 3 is not supported now by the contract backend, and I suggest leaving it to further discussion.

**Comment by TiGowa** [comment]
'Instant Swap' is a wrapper of what is today three different actions:
1. Deposit
2. Swap
3. Withdraw 

The feature would allow users to swap instantly, therefore improving the user experience for a specific use case vs. active trading on the platform. For examples:

- Swap NEAR for DAI to bet on a specific Pulse market (Ref used as a bridge for another NEAR Dapp interaction)
- Swap REF for NEAR then send NEAR to Binance to lend NEAR (specific financial use case)
- Etc.

A note on the notion of 'instant order' in the crypto ecosystem / exchange semantics. For example, Bitstamp defines an instant order as: 

> An instant order is an order type, which executes immediately under the current price on the market and is therefore **simple** to use. We recommend instant orders **for users who would like to make a trade immediately**.
_Source: https://www.bitstamp.net/faq/instant-order/_

An instant swap would then be aligned with both market terms / qualifications in Ref's proposal: simple and immediate.

Regading the UI and just for infromation, 'Instant' is displayed as an order type on a Central Limit Order Book type of exchange.

<img width="270" alt="Screenshot 2021-09-07 at 10 20 06" src="https://user-images.githubusercontent.com/46521065/132535598-ffee4644-e42b-4c9d-b7c9-99040a2b234c.png">

Regarding the implementation of such a feature on Ref, I think we have two main challenges: 
1. **At the contract level**: what are the risks of execution? For example, if a. Deposit b. Swap and c. Withdraw, there are 8 outcome scenarios, taking the assumption that one action results in either OK or KO (failed). Plus, what is the impact of such a scenario. For example, if the user hasn't registered to the output token the withdrawal would fail, resulting in the token locked in the FT contract. The impact would then be qualified as 'high', although funds are not lost, sending them back to the swapper would require an action from the owner of the FT contract.  

2. At the UI level: how to not confuse the user with the coexistence of both 'as is' and 'instant' swap?

On two, @aidai524 initially suggested to add a tab 'Instant Swap', letting users selecting the feature and having by default the 'as is' swap. Second option was to have the 'Instant Swap' directly on the landing page.

I prefer and would advocate / push for option 1. Having 'Instant Swap' will address specific users as mentioned above. Moreover, as liquidity provision still requires users to deposit funds first, it would be 'weird' to push for Instant Swap on the frontend if not ALL actions on the platfrom can be done without depositing and withdrawing. 

Apart from my mistake, there are not similar AMMs with two swap modes we can get inspiration from on the UI side. DyDx (not an AMM) is interesting as it has a deposit mode before trading. 

<img width="325" alt="Screenshot 2021-09-08 at 17 33 26" src="https://user-images.githubusercontent.com/46521065/132548956-e8aa93d7-1c8b-434c-8403-6ee3202c458e.png">

Finally, having a deposit mode can be useful as Ref scales, in addressing new features (margin, lending) where Deposit might be a requirement.

**Comment by marco-sundsk** [comment]
> A note on the notion of 'instant order' in the crypto ecosystem / exchange semantics. For example, Bitstamp defines an instant order as:
> 
> > An instant order is an order type, which executes immediately under the current price on the market and is therefore **simple** to use. We recommend instant orders **for users who would like to make a trade immediately**.
> > _Source: https://www.bitstamp.net/faq/instant-order/_
> 
> An instant swap would then be aligned with both market terms / qualifications in Ref's proposal: simple and immediate.

I like that idea. It makes `instant swap` kind of more identifiable at the same time keeps deposit/withdraw system intact.

> 1. **At the contract level**: what are the risks of execution? For example, if a. Deposit b. Swap and c. Withdraw, there are 8 outcome scenarios, taking the assumption that one action results in either OK or KO (failed). Plus, what is the impact of such a scenario. For example, if the user hasn't registered to the output token then the withdrawal would fail, resulting in the token locked in the FT contract. The impact would then be qualified as 'high', although funds are not lost, sending them back to the swapper would require an action from the owner of the FT contract.

I can explain the security model here: Let's call three actions as D (deposit), S (swap) and W (withdraw), actually, there are following possiblities:
* D fails, All token deposited will stay in user's wallet, that is to say, the deposit is cancelled. It is guaranteed by FT standard;
* D passes, S fails: Cause S action is executed in the FT ft_on_transfer_call routine, still, any error would cause the deposit be cancelled. That is to say, like D fails, the deposited token will remain in user's wallet.
* D passes, S passes, W fails: Then comes the situation we need to take care of, if User has an inner account in ref, (which means he deposited some token in the past, maybe a LP, and have enought storage fee locked), the swapped out token would be recorded into that inner account and user has to withdraw them explicitly. And if no inner account exists, then the swapped out token has to go to contract owner's inner account, we call it `lostfound`. And user has to contact the owner (generally would be the ref DAO) to claim their token.  

Anyway, no token would loss during the whole process.

**Comment by aidai524** [comment]
> On two, @aidai524 initially suggested to add a tab 'Instant Swap', letting users selecting the feature and having by default the 'as is' swap. Second option was to have the 'Instant Swap' directly on the landing page, pushing users towards that type of swap.
> 
> I prefer option 1. Having 'Instant Swap' will address specific users as mentioned above. Moreover, as liquidity provision still requires users to deposit funds first, it would be 'weird' to push for Instant Swap on the frontend if not ALL actions on the platform can be done without depositing and withdrawing.

I also prefer option 1, but this option is more like a temporary one.

In the future, I think we should cancel deposit swap, and any user can use the balance in the wallet for instant swap. We only need users to perform deposit operations when users add liquidity. If the user has not added liquidity, deposit is not an inevitable operation of using Ref.
